parameters:
    exercise.knight.handler.class: ExerciseBundle\Handler\KnightHandler
    exercise.knight.class: ExerciseBundle\Entity\Knight
    exercise.arena.class: ExerciseBundle\Services\Arena

services:
    exercise.knight.handler:
        class: %exercise.knight.handler.class%
        arguments: [ @doctrine.orm.entity_manager, %exercise.knight.class%, @form.factory ]

    exercise.arena:
        class: %exercise.arena.class%
